# Change the prefix, because CTRL-A is frankly superior in every way
# NOTE(2026-03-10): I've grown used to CTRL-B at work where I don't get a
# choice. Returning to default.
#set -g prefix C-a

# Unbinding the original prefix allows us to use it normally on hosts
# configured with the default
#unbind-key C-b

# Allow me to set names
set -g allow-rename off

# Be lazy, use the mouse
set -g mouse on

# Start at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Increase scrollback size bigtime
set -g history-limit 50000
