# Change the prefix, because CTRL-A is frankly superior in every way
set -g prefix C-a

# Unbinding the original prefix allows us to use it normally on hosts
# configured with the default
unbind-key C-b

# Allow me to set names
set -g allow-rename off

# Be lazy, use the mouse
set -g mouse on