# Uncomment to make vscode look sharper on fractional scaling displays under
# Wayland. Be forewarned that it might crash way more often and just generally
# be buggier.
#--enable-features=UseOzonePlatform
#--ozone-platform=Wayland
