add_newline = false
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$rust\
$golang\
$python\
$nodejs\
$terraform\
$helm\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$java\
$julia\
$nim\
$ocaml\
$perl\
$php\
$purescript\
$ruby\
$swift\
$zig\
$nix_shell\
$conda\
$crystal\
$cmd_duration\
$line_break\
$jobs\
$status\
$character"""
# List of removed modules
# $shlvl
# $hg_branch
# $env_var
# $battery
# $time
# $custom
# $memory_usage
# $kubernetes
# $gcloud
# $openstack
# $aws
# $docker_context

[aws]
disabled = true

[character]
success_symbol = "[﬌](bold green)"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold green)"

[directory]
read_only = ""

[gcloud]
disabled = true

[git_branch]
symbol = " "

[git_commit]
tag_disabled = false

[git_status]
format = "$ahead_behind$all_status"
conflicted = "!!"
ahead = "[⌃$count](bold cyan) "
behind = "[⌄$count](bold cyan) "
diverged = "[ ⌃$ahead_count ⌄$behind_count](bold purple) "
untracked = "[✗$count](bold red) "
stashed = "[$count](bold blue) "
modified = "[∆$count](bold yellow) "
staged = "[✔$count](bold green) "
renamed = "[凜$count](bold yellow) "
deleted = "[-$count](bold red) "

[golang]
symbol = " "

[hostname]
ssh_only = false
style = "bold green"

[jobs]
symbol = "累 "

[openstack]
disabled = true

[package]
display_private = true

[username]
style_user = "bold blue"
format = "[$user]($style) on "
show_always = true